import type { Metadata } from "next";
import "@/app/globals.css";
import SideBar from "@/components/SideBar";
import NavBar from "@/components/Navbar";
import Stars from "@/components/Stars";
import MSideBar from "@/components/MobileSideBar";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div className="min-h-screen absolute inset-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_10px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:14px_24px] z-0"></div> */}

        <Stars />

        <div className="overflow-auto flex text-white items-center justify-center m-2 sm:my-10 sm:mx-40 flex-col sm:flex-row relative z-10">
          <MSideBar />
          <SideBar/>
          <main className="flex text-white relative justify-center items-center w-full sm:w-auto">
            <section className="flex-1 bg-[#130e0e2e] rounded-2xl my-4 p-8 overflow-auto h-screen border-2 border-orange-400 relative">
              <div className="absolute right-4 top-4 z-15 hidden  sm:block">
                <NavBar />
              </div>
              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
